### ISSUE TITLE
Fix `Last updated on...`

### ISSUE THREAD

**Issue by omarcostahamido** [Quantumland-art/community#46]
I actually have no idea how to fix this one yet...
All database and faqs pages include a last edit on tag at the top. it is currently not working.
currently it changes this date of all pages regardless of them being updated or not, everytime the site is deployed. (quite frankly that might be why). It does work on local deployment 'cause old pages stay on file

**Comment by ntrocado** [comment]
Did you try this workaround?: https://github.com/gjtorikian/jekyll-last-modified-at/issues/69#issuecomment-1327968584

**Comment by omarcostahamido** [comment]
oh hi @ntrocado 
sorry i'm only seeing this now (long week)
This is very interesting workaround, I didn't know about it.
We should try it.
